In [1]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [2]:
[1, 2, 3] + [1, 2, 3] + [1, 2, 3]

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
[1, 2, 3] * [4, 5, 6]

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
[3, 6, 9]

# Numpy (Numerical Python) 

> `Numpy` merupakan package di python yang sering digunakan untuk melakukan operasi matematik.

In [4]:
import numpy as np #np adalah singkatan dan merupakan konsensus

In [5]:
# membuat matrik menggunakan numpy array
a = np.array([1, 2, 3])

In [6]:
# operasi matematik pada numpy array
a * 3

array([3, 6, 9])

In [7]:
a + a

array([2, 4, 6])

In [8]:
np.array([1, 2, 3]) + np.array([1, 2, 3])

array([2, 4, 6])

# Fungsi Matematika 

In [9]:
a

array([1, 2, 3])

In [10]:
# menjumlahkan seluruh data yang ada pada matriks
np.sum(a)

6

In [11]:
# mencari rata-rata dari data yang ada pada matriks
np.mean(a)

2.0

In [16]:
# mencari standard deviasi dari matriks
std = np.std(a)

In [17]:
std**2

0.6666666666666666

#  Arange, Linspace, Logspace

> Arange, linspace dan logspace digunakan untuk membuat matriks dengan rule tertentu.

In [23]:
for i in range(len(a)):
    print(i)

0
1
2


Input dari np.arrange adalah:
- start (matriks mulai dari angka berapa)
- end (nilai akhir dari matriks)
- step (jarak antara data pada matriks)

Pada np.arange, berlaku juga hukum inclusive, exclusive.

In [24]:
np.arange(0, 10+1, 2)

array([ 0,  2,  4,  6,  8, 10])

In [25]:
# membuat linear space matriks dengan start 0, end 10, sebanyak 5 data
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
# membuat logaritmic space matriks dengan start di pangkat -3, end di pangkat 3, dan jumlah data 7
np.logspace(-3, 3, 7)

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

# Random 

In [79]:
# membuat nilai random, input parameter adalah (jumlah row, jumlah kolom)
# berdasarkan dokumentasi numpy, nilai rand yang dihasilkan adalah dari 0 hingga 1
np.random.rand(3, 3)

array([[0.25813882, 0.65585365, 0.10265688],
       [0.09569864, 0.03839155, 0.40462133],
       [0.2943839 , 0.22385151, 0.86804447]])

# Controlled Randomness 

> Controlled Randomness sangat penting untuk membuat code yang reproducible sehingga kita bisa membandingkan performa antar model pada machine learning.

In [70]:
# input dari randomstate bebas angka berapa saja, jika kita membuat angka random dengan randomstate yang sama 
# maka nilai random yang keluar akan selalu sama
state = np.random.RandomState(30)
state.rand(3)

array([0.64414354, 0.38074849, 0.66304791])

In [61]:
state = np.random.RandomState(442)
state.rand(3)

array([0.39467617, 0.19820664, 0.25483107])